# Generated by Django 5.2 on 2025-04-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('publisher', 'Publisher'), ('reader', 'Reader')], default='reader', max_length=50),
        ),
    ]
