# Generated by Django 5.2 on 2025-04-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_author_is_deleted_book_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/%Y/%m/%d'),
        ),
    ]
